spring.application.name=showflix

spring.datasource.url=jdbc:mysql://localhost:3306/showflix
spring.datasource.username=root
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=showflixSecretKey2026SuperSeguroParaJwtTokenAuthentication123456
jwt.expiration=86400000
